---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Template configuration"
        Parameters:
          - BundleS3HttpsLocation
          - Stage
    ParameterLabels:
      BundleS3HttpsLocation:
        default: "The https S3 location of where quicksight nested stacks are stored"

Parameters:
  BundleS3HttpsLocation:
    Type: String
    Default: "https://quicksight-bundling-demo-888519273200.s3.amazonaws.com"
  Stage:
    Type: String
    Default: 'DEV'

Mappings:
  DataSourcesConfiguration:
    DEV:
      DataSourceVpcConnectionArn: arn:aws:quicksight:us-east-1:888519273200:vpcConnection/DefaultVpcConnection
      DataSourcePort: 5432
      DataSourceHost: devportal-cluster.cluster-cufe1iwohaxm.us-east-1.rds.amazonaws.com
      DataSourceDatabase: session_state_store
      DataSourcePassword: abc123!@#
      DataSourceUsername: xrunzhi

Resources:
  QSThemeStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL:
        Fn::Join:
          - /
          - - Ref: BundleS3HttpsLocation
            - quicksight
            - sampleTheme.template.yml

  QSDataSourceStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      Parameters:
        DataSourceUsername:
          Fn::FindInMap:
          - DataSourcesConfiguration
          - Ref: Stage
          - DataSourceUsername
        DataSourcePassword:
          Fn::FindInMap:
          - DataSourcesConfiguration
          - Ref: Stage
          - DataSourcePassword
        DataSourceDatabase:
          Fn::FindInMap:
          - DataSourcesConfiguration
          - Ref: Stage
          - DataSourceDatabase
        DataSourceHost:
          Fn::FindInMap:
          - DataSourcesConfiguration
          - Ref: Stage
          - DataSourceHost
        DataSourcePort:
          Fn::FindInMap:
          - DataSourcesConfiguration
          - Ref: Stage
          - DataSourcePort
        DataSourceVpcConnectionArn:
          Fn::FindInMap:
          - DataSourcesConfiguration
          - Ref: Stage
          - DataSourceVpcConnectionArn
      TemplateURL:
        Fn::Join:
          - /
          - - Ref: BundleS3HttpsLocation
            - quicksight
            - sampleDataSource.template.yml

  QSDataSetStack:
    DependsOn: QSDataSourceStack
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      Parameters:
        SampleDataSourceArn:
          Fn::GetAtt:
            - QSDataSourceStack
            - Outputs.SampleDataSourceArn
      TemplateURL:
        Fn::Join:
          - /
          - - Ref: BundleS3HttpsLocation
            - quicksight
            - sampleDataSet.template.yml

  QSTemplateStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL:
        Fn::Join:
          - /
          - - Ref: BundleS3HttpsLocation
            - quicksight
            - sampleTemplate.template.yml

  QSDashboardStack:
    DependsOn:
    - QSDataSourceStack
    - QSDataSetStack
    - QSThemeStack
    - QSAnalysisStack
    - QSTemplateStack
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      Parameters:
        TemplateArn:
          Fn::GetAtt:
            - QSTemplateStack
            - Outputs.SampleTemplateArn
        ThemeArn:
          Fn::GetAtt:
            - QSThemeStack
            - Outputs.SampleThemeArn
        DataSetArn:
          Fn::GetAtt:
            - QSDataSetStack
            - Outputs.SampleDataSetArn
      TemplateURL:
        Fn::Join:
          - /
          - - Ref: BundleS3HttpsLocation
            - quicksight
            - sampleDashboard.template.yml

  QSAnalysisStack:
    DependsOn: QSTemplateStack
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      Parameters:
        TemplateArn:
          Fn::GetAtt:
            - QSTemplateStack
            - Outputs.SampleTemplateArn
        DataSetArn:
          Fn::GetAtt:
            - QSDataSetStack
            - Outputs.SampleDataSetArn
      TemplateURL:
        Fn::Join:
          - /
          - - Ref: BundleS3HttpsLocation
            - quicksight
            - sampleAnalysis.template.yml
