---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "DataSource Configuration"
        Parameters:
          - DataSourceVpcConnectionArn
          - DataSourceUsername
          - DataSourcePassword
          - DataSourceHost
          - DataSourcePort
          - DataSourceDatabase
      - Label:
          default: " configuration"
        Parameters:
          - BundleS3HttpsLocation
    ParameterLabels:
      DataSourceVpcConnectionArn:
        default: "Which VPC connection should be used for data source"
      BundleS3HttpsLocation:
        default: "The https S3 location of where quicksight nested stacks are stored"


Parameters:
  BundleS3HttpsLocation:
    Type: String
    Default: "https://quicksight-bundling-demo-888519273200.s3.amazonaws.com"
  DataSourceUsername:
    Type: String
    Default: "xrunzhi"
  DataSourcePassword:
    Type: String
    Default: "abc123!@#"
  DataSourceDatabase:
    Type: String
    Default: "session_state_store"
  DataSourceHost:
    Type: String
    Default: "devportal-cluster.cluster-cufe1iwohaxm.us-east-1.rds.amazonaws.com"
  DataSourcePort:
    Type: Number
    Default: 5432
  DataSourceVpcConnectionArn:
    Type: String
    Default: "arn:aws:quicksight:us-east-1:888519273200:vpcConnection/DefaultVpcConnection"

Resources:
  QSThemeStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL:
        Fn::Join:
          - /
          - - Ref: BundleS3HttpsLocation
            - quicksight
            - sampleTheme.template.yml

  QSDataSourceStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      Parameters:
        DataSourceUsername:
          Ref: DataSourceUsername
        DataSourcePassword:
          Ref: DataSourcePassword
        DataSourceDatabase:
          Ref: DataSourceDatabase
        DataSourceHost:
          Ref: DataSourceHost
        DataSourcePort:
          Ref: DataSourcePort
        DataSourceVpcConnectionArn:
          Ref: DataSourceVpcConnectionArn
      TemplateURL:
        Fn::Join:
          - /
          - - Ref: BundleS3HttpsLocation
            - quicksight
            - sampleDataSource.template.yml

  QSDataSetStack:
    DependsOn: QSDataSourceStack
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      Parameters:
        SampleDataSourceArn:
          Fn::GetAtt:
            - QSDataSourceStack
            - Outputs.SampleDataSourceArn
      TemplateURL:
        Fn::Join:
          - /
          - - Ref: BundleS3HttpsLocation
            - quicksight
            - sampleDataSet.template.yml

  QSTemplateStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL:
        Fn::Join:
          - /
          - - Ref: BundleS3HttpsLocation
            - quicksight
            - sampleTemplate.template.yml

  QSDashboardStack:
    DependsOn:
    - QSDataSourceStack
    - QSDataSetStack
    - QSThemeStack
    - QSAnalysisStack
    - QSTemplateStack
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      Parameters:
        TemplateArn:
          Fn::GetAtt:
            - QSTemplateStack
            - Outputs.SampleTemplateArn
        ThemeArn:
          Fn::GetAtt:
            - QSThemeStack
            - Outputs.SampleThemeArn
      TemplateURL:
        Fn::Join:
          - /
          - - Ref: BundleS3HttpsLocation
            - quicksight
            - sampleDashboard.template.yml

  QSAnalysisStack:
    DependsOn: QSTemplateStack
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      Parameters:
        TemplateArn:
          Fn::GetAtt:
            - QSTemplateStack
            - Outputs.SampleTemplateArn
      TemplateURL:
        Fn::Join:
          - /
          - - Ref: BundleS3HttpsLocation
            - quicksight
            - sampleAnalysis.template.yml
