---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Template configuration"
        Parameters:
          - BundleS3HttpsLocation
          - Stage
    ParameterLabels:
      BundleS3HttpsLocation:
        default: "The https S3 location of where quicksight nested stacks are stored"

Parameters:
  BundleS3HttpsLocation:
    Type: String
    Default: "https://quicksight-bundling-demo-888519273200.s3.amazonaws.com"
  Stage:
    Type: String
    Default: 'DEV'
  QuickSightUser:
    Type: String
    Default: 'Admin/xrunzhi-Isengard'

Mappings:
  DataSourcesConfiguration:
    DEV:
      DataSourceVpcConnectionArn: DefaultVpcConnection
      DataSourcePort: 5432
      DataSourceHost: devportal-cluster.cluster-cufe1iwohaxm.us-east-1.rds.amazonaws.com
      DataSourceDatabase: session_state_store
      DataSourcePassword: abc123!@#
      DataSourceUsername: xrunzhi
    TEST:
      DataSourceVpcConnectionArn: DefaultTestConnection
      DataSourcePort: 5432
      DataSourceHost: devportal-cluster.cluster-cys61g8smssb.us-east-1.rds.amazonaws.com
      DataSourceDatabase: session_state_store
      DataSourcePassword: abc123!@#
      DataSourceUsername: testuser
    PROD:
      DataSourceVpcConnectionArn: DefaultProdConnection
      DataSourcePort: 5432
      DataSourceHost: devportal-cluster.cluster-clfm2rn5giqf.us-east-1.rds.amazonaws.com
      DataSourceDatabase: session_state_store
      DataSourcePassword: iop890*()
      DataSourceUsername: produser
  DashaboardConfiguration:
    DEV:
      DataSetArn: arn:aws:quicksight:us-east-1:888519273200:dataset/926a5dbb-deea-4ea5-b2be-7ef7655cf247
    TEST:
      DataSetArn: arn:aws:quicksight:us-east-1:996044087377:dataset/5661e8ca-053c-4a65-9ce6-ee6b0a1e588c
    PROD:
      DataSetArn: arn:aws:quicksight:us-east-1:827082787819:dataset/bf6b0815-cc14-42fa-aaad-ba306e531d7d

Resources:

  QSDataSourceStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      Parameters:
        QuickSightUser:
          Ref: QuickSightUser
        DataSourceUsername:
          Fn::FindInMap:
          - DataSourcesConfiguration
          - Ref: Stage
          - DataSourceUsername
        DataSourcePassword:
          Fn::FindInMap:
          - DataSourcesConfiguration
          - Ref: Stage
          - DataSourcePassword
        DataSourceDatabase:
          Fn::FindInMap:
          - DataSourcesConfiguration
          - Ref: Stage
          - DataSourceDatabase
        DataSourceHost:
          Fn::FindInMap:
          - DataSourcesConfiguration
          - Ref: Stage
          - DataSourceHost
        DataSourcePort:
          Fn::FindInMap:
          - DataSourcesConfiguration
          - Ref: Stage
          - DataSourcePort
        DataSourceVpcConnectionArn:
          Fn::FindInMap:
          - DataSourcesConfiguration
          - Ref: Stage
          - DataSourceVpcConnectionArn
      TemplateURL:
        Fn::Join:
          - /
          - - Ref: BundleS3HttpsLocation
            - quicksight
            - sampleDataSource.template.yml

  QSDataSetStack:
    DependsOn: QSDataSourceStack
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      Parameters:
        QuickSightUser:
          Ref: QuickSightUser
        SampleDataSourceArn:
          Fn::GetAtt:
            - QSDataSourceStack
            - Outputs.SampleDataSourceArn
      TemplateURL:
        Fn::Join:
          - /
          - - Ref: BundleS3HttpsLocation
            - quicksight
            - sampleDataSet.template.yml

  QSTemplateStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      Parameters:
        QuickSightUser:
          Ref: QuickSightUser
      TemplateURL:
        Fn::Join:
          - /
          - - Ref: BundleS3HttpsLocation
            - quicksight
            - sampleTemplate.template.yml

  QSDashboardStack:
    DependsOn:
    - QSDataSourceStack
    - QSDataSetStack
    - QSAnalysisStack
    - QSTemplateStack
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      Parameters:
        QuickSightUser:
          Ref: QuickSightUser
        TemplateArn:
          Fn::GetAtt:
            - QSTemplateStack
            - Outputs.SampleTemplateArn
        SessionTemplateArn:
          Fn::GetAtt:
            - QSTemplateStack
            - Outputs.SampleSessionTemplateArn
        SessionDataSetArn:
          Fn::GetAtt:
            - QSDataSetStack
            - Outputs.SampleDataSetArn
        ThemeArn:
          Fn::ImportValue:
            SingleStackThemeArn
        DataSetArn:
          Fn::FindInMap:
            - DashaboardConfiguration
            - Ref: Stage
            - DataSetArn
      TemplateURL:
        Fn::Join:
          - /
          - - Ref: BundleS3HttpsLocation
            - quicksight
            - sampleDashboard.template.yml

  QSAnalysisStack:
    DependsOn: QSTemplateStack
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      Parameters:
        QuickSightUser:
          Ref: QuickSightUser
        TemplateArn:
          Fn::GetAtt:
            - QSTemplateStack
            - Outputs.SampleTemplateArn
        DataSetArn:
          Fn::FindInMap:
            - DashaboardConfiguration
            - Ref: Stage
            - DataSetArn
        SessionTemplateArn:
          Fn::GetAtt:
            - QSTemplateStack
            - Outputs.SampleSessionTemplateArn
        SessionDataSetArn:
          Fn::GetAtt:
            - QSDataSetStack
            - Outputs.SampleDataSetArn
      TemplateURL:
        Fn::Join:
          - /
          - - Ref: BundleS3HttpsLocation
            - quicksight
            - sampleAnalysis.template.yml
