---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  BundleS3HttpsLocation:
    Type: String
    Default: "https://sam-dev-us-east-1-xrunzhi-qsasset-888519273200.s3.amazonaws.com/demo/QuickSightResources"
  DataSourceUsername:
    Type: String
    Default: "xrunzhi"
  DataSourcePassword:
    Type: String
    Default: "abc123!@#"
  DataSourceDatabase:
    Type: String
    Default: "session_state_store"
  DataSourceHost:
    Type: String
    Default: "devportal-cluster.cluster-cufe1iwohaxm.us-east-1.rds.amazonaws.com"
  DataSourcePort:
    Type: Number
    Default: 5432
  DataSourceVpnConnectionArn:
    Type: String
    Default: "arn:aws:quicksight:us-east-1:888519273200:vpcConnection/DefaultVpcConnection"

Resources:
  QSThemeStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL:
        Fn::Join:
          - /
          - - Ref: BundleS3HttpsLocation
            - nestedStacks
            - sampleTheme.template.yml

  QSDataSourceStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      Parameters:
        DataSourceUsername:
          Ref: DataSourceUsername
        DataSourcePassword:
          Ref: DataSourcePassword
        DataSourceDatabase:
          Ref: DataSourceDatabase
        DataSourceHost:
          Ref: DataSourceHost
        DataSourcePort:
          Ref: DataSourcePort
        DataSourceVpnConnectionArn:
          Ref: DataSourceVpnConnectionArn
      TemplateURL:
        Fn::Join:
          - /
          - - Ref: BundleS3HttpsLocation
            - nestedStacks
            - sampleDataSource.template.yml

  QSDataSetStack:
    DependsOn: QSDataSourceStack
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      Parameters:
        SampleDataSourceArn:
          Fn::GetAtt:
            - QSDataSourceStack
            - Outputs.SampleDataSourceArn
      TemplateURL:
        Fn::Join:
          - /
          - - Ref: BundleS3HttpsLocation
            - nestedStacks
            - sampleDataSet.template.yml

  QSTemplateStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL:
        Fn::Join:
          - /
          - - Ref: BundleS3HttpsLocation
            - nestedStacks
            - sampleTemplate.template.yml

  QSDashboardStack:
    DependsOn:
    - QSDataSourceStack
    - QSDataSetStack
    - QSThemeStack
    - QSAnalysisStack
    - QSTemplateStack
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      Parameters:
        TemplateArn:
          Fn::GetAtt:
            - QSTemplateStack
            - Outputs.SampleTemplateArn
        ThemeArn:
          Fn::GetAtt:
            - QSThemeStack
            - Outputs.SampleThemeArn
      TemplateURL:
        Fn::Join:
          - /
          - - Ref: BundleS3HttpsLocation
            - nestedStacks
            - sampleDashboard.template.yml

  QSAnalysisStack:
    DependsOn: QSTemplateStack
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      Parameters:
        TemplateArn:
          Fn::GetAtt:
            - QSTemplateStack
            - Outputs.SampleTemplateArn
      TemplateURL:
        Fn::Join:
          - /
          - - Ref: BundleS3HttpsLocation
            - nestedStacks
            - sampleAnalysis.template.yml
