---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  TemplateArn:
    Type: String
  DataSetArn:
    Type: String
  QuickSightUser:
    Type: String

Resources:
  SampleAnalysis:
    Type: AWS::QuickSight::Analysis
    Properties:
      AwsAccountId:
        Ref: AWS::AccountId
      AnalysisId: 'xrunzhi-sample-analysis-id-v3'
      Name: 'xrunzhi-sample-analysis-name-v3'
      SourceEntity:
        SourceTemplate:
          Arn:
            Ref: TemplateArn
          DataSetReferences:
            - DataSetPlaceholder: 'inventory-dataset-placeholder'
              DataSetArn:
                Ref: DataSetArn
              #DataSetArn: !Sub 'arn:aws:quicksight:us-east-1:${AWS::AccountId}:dataset/926a5dbb-deea-4ea5-b2be-7ef7655cf247'
      Permissions:
        - Principal: !Sub
          - arn:aws:quicksight:${AWS::Region}:${AWS::AccountId}:user/default/Admin/${user}
          - { user: !Ref: QuickSightUser }
          Actions:
            - quicksight:RestoreAnalysis
            - quicksight:UpdateAnalysisPermissions
            - quicksight:DeleteAnalysis
            - quicksight:QueryAnalysis
            - quicksight:DescribeAnalysisPermissions
            - quicksight:DescribeAnalysis
            - quicksight:UpdateAnalysis