---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  QuickSightUser:
    Type: String

Outputs:
  SampleTemplateArn:
    Value:
      Fn::GetAtt:
        - SampleTemplate
        - Arn
  SampleSessionTemplateArn:
    Value:
      Fn::GetAtt:
        - SampleTemplateSession
        - Arn

Resources:
  SampleTemplate:
    Type: AWS::QuickSight::Template
    Properties:
      AwsAccountId:
        Ref: AWS::AccountId
      TemplateId: 'bundle-asset-sample-id-v3'
      Name: 'bundle-asset-sample-name-v3'
      SourceEntity:
        SourceTemplate:
          Arn: 'arn:aws:quicksight:us-east-2:266266396604:template/inventory-dataset-placeholder-id'
      Permissions:
        - Principal:
            Fn::Sub:
              - arn:aws:quicksight:${AWS::Region}:${AWS::AccountId}:user/default/${username}
              - username:
                  Ref: QuickSightUser
          Actions:
            - quicksight:CreateTemplate
            - quicksight:DescribeTemplate
            - quicksight:ListTemplates
            - quicksight:DescribeTemplatePermissions
            - quicksight:DeleteTemplate
            - quicksight:UpdateTemplate
  SampleTemplateSession:
    Type: AWS::QuickSight::Template
    Properties:
      AwsAccountId:
        Ref: AWS::AccountId
      TemplateId: 'SampleSessionTemplate'
      Name: 'SampleSessionTemplate'
      SourceEntity:
        SourceTemplate:
          Arn: 'arn:aws:quicksight:us-east-2:266266396604:template/session-sample-template'
      Permissions:
        - Principal:
            Fn::Sub:
              - arn:aws:quicksight:${AWS::Region}:${AWS::AccountId}:user/default/${username}
              - username:
                  Ref: QuickSightUser
          Actions:
            - quicksight:CreateTemplate
            - quicksight:DescribeTemplate
            - quicksight:ListTemplates
            - quicksight:DescribeTemplatePermissions
            - quicksight:DeleteTemplate
            - quicksight:UpdateTemplate